# Generated by Django 6.1 on 2026-08-31 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(help_text='Full URL including scheme and port, e.g. http://102.22.232.42:8296/', max_length=500, unique=True)),
                ('check_interval_seconds', models.PositiveIntegerField(default=60, help_text='How often (seconds) this IP is checked.')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, help_text='Request timeout (seconds) before considered down.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause monitoring without deleting.')),
                ('current_status', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_up_at', models.DateTimeField(blank=True, null=True)),
                ('last_down_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
