# Generated by Django 5.2.17 on 2026-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimeip',
            name='current_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='down', max_length=10),
        ),
    ]
