# Generated by Django 5.2.17 on 2026-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_alter_uptimeip_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimeip',
            name='current_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='uptimeip',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Request timeout (seconds) before considered down.'),
        ),
    ]
